default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: sample_ec_development

  <<: *default
  database: sample_ec_test

production:
  <<: *default
  database: sample_ec_production
  username: sample_ec
  password: <%= ENV['SAMPLE_EC_DATABASE_PASSWORD'] %>
